# -*- coding: utf-8 -*-
"""Student Mental Health Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uR-5GuxtQ44OdAK8bgzVKWBT1Niy3tN6

# Student Mental Health EDA

Mental health is a very imortant part of our overall health and wellbeing. By understanding how illnesses like anxiety or depression affect certain groups of people, we will be better able to guide them to resources that are able to deal and treat these issues.

In this analysis, we will be looking at and examining mental illnesses amongst college students. We will see how certain majors play a role into possibly contributing to these health issues and the impact it may play on one's ability to succeed academically.
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

"""Let's start by reading in our csv file titled "Student Mental Health."
"""

df = pd.read_csv('Student Mental health.csv')
df.head(15)

"""Let's change the column names to make them more concise and managable."""

df.columns = ['Timestamp', 'Gender', 'Age', 'Major', 'Year', 'GPA', 'Marital_Status', 'Depression', 'Anxiety', 'Panic_Attack', 'Treatment']

"""Here, we'll get a brief overview of our data. We see that the Age column has one missing value."""

df.info()

"""Dropping the row with the Nan value now gives us a complete workable dataset."""

#Age has a nan value to drop
df= df.dropna()
df.info()

"""Here, we noticed that the GPA column consisted of entries made up of ranges. We decide to simplify it my taking the avergae of the range values."""

# converting the GPA ranges to their mean

def range_convert(str):
    str = str.strip()
    lower_bound = str[:str.index("-")]
    upper_bound =str[str.index("-")+1: ]
    gpa_mean = (float(lower_bound) + float(upper_bound))/2
    return gpa_mean

df["GPA"] = df["GPA"].apply(range_convert)
df['GPA']

"""Looking at the Year column, we see that it has inconsistent letter casing. To fix this, we decide to do away with the "year" wprd and convert the entries to the number only."""

#year is formatted strangely
df['Year'].unique()

def reformat_year(yr_str):
    yr_str = yr_str[-1]
    yr_str = int(yr_str)
    return yr_str
df["Year"] = df["Year"].apply(reformat_year)
df['Year'].unique()

"""Looking at the major column, we noticed that it had a few redundant names that referred to the same major. Let's fix this to make everything a bit more uniform."""

df['Major'].unique()

#replace redundant course name with reg course name
df['Major'].replace({ 'BIT':'IT', 'Benl': 'BENL', 'engin': 'Engineering' , 'Engine':'Engineering' , 'Fiqh fatwa ': 'Fiqh', 'Islamic education':'Islamic Education' , 'koe': 'Koe', 'Kirkhs': 'Irkhs', 'KIRKHS': 'Irkhs', 'Laws': 'Law', 'Pendidikan islam':'Pendidikan Islam' , 'psychology':'Psychology'} , inplace = True)

"""## Analyzing Data

In this section, we are gong to examine the data and look for possible trends in the dataset.
"""

plt.figure(figsize=(10,5))
axis = df["Age"].hist(bins=15, density=True)
df["Age"].plot(kind='density')
plt.show()
plt.savefig('age_hist.png')

"""#Inference:
- Students in this dataset are aged from 18-24 (young adults) with a majority of data coming from students aged 18-19 and 23-24.
- Why such little info from the middle age group? Could 20-22 have mental health issues that affects ability to respond?

#Examining the connection between one's major and their current school year
"""

# Year 1
plt.figure(figsize=(10, 5))
chart = sns.countplot(x = 'Major', data = df[df['Year'] == 1])  #get a course count where the year is = to 1
chart.set_xticklabels(chart.get_xticklabels(), rotation=90)
plt.savefig('year1.png')

"""#Inference for Year 1:
- Most Year 1 students major in Engineering and Computer Science with a few in IT.
"""

#Year 2

plt.figure(figsize=(10, 5))
chart = sns.countplot(x = 'Major', data = df[df['Year'] == 2])
chart.set_xticklabels(chart.get_xticklabels(), rotation=90)
plt.savefig('year2.png')

"""#Inference for Year 2
- Most Year 2 students major in Engineering and Computer Science with a few in KOE.
"""

#Year 3

plt.figure(figsize=(10, 5))
chart = sns.countplot(x = 'Major', data = df[df['Year'] == 3])
chart.set_xticklabels(chart.get_xticklabels(), rotation=90)
plt.savefig('year3.png')

"""#Inference for Year 3
- Most Year 3 students major in IT with an near even amount also majoring in Computer Science or Law.
"""

#Year 4

plt.figure(figsize=(10,5))
chart = sns.countplot(x = 'Major', data = df[df['Year'] == 4])
chart.set_xticklabels(chart.get_xticklabels(), rotation=90)
plt.savefig('year4.png')

"""#Inference for Year 4
- Most Year 4 students major in Engineering.
- We also see that some other majors are no longer listed. Could it be that they switched or dropped out?


#Overall:
- A majority of students have majored in Engineering, Comp Sci or IT over the depicted 4 years.

#Examining the connection between Depression, Anxiety, and Panic Attacks with one's chosen major

Is there a major that tends to have a higher rate of mental health issues amongst it's students? Let's take a look.
"""

# Depression analysis amongst all courses

plt.figure(figsize=(8, 8))
sns.stripplot(x = 'Depression', y = 'Major', hue = 'Gender', data = df)
plt.show()
plt.savefig('depression.png')

"""#Inference for Depression:
- Of all the majors, Computer Science, IT, and Engineering have the most students who experience anxiety; however, of the students majoring in Comp. Sci. and Engineering, many do not experience these feelings..
- Around 50% of the students in IT experience depression.
- Men experience anxiety at a lower rate than women. Why is that? Could it be because these tend to be male dominated fields leading to feelings of isolation?
"""

#Anxiety analysis amongst all courses

plt.figure(figsize=(8, 8))
sns.stripplot(x = 'Anxiety', y = 'Major', hue = 'Gender', data = df)
plt.show()
plt.savefig('anxiety.png')

"""#Inference for Anxiety:
- Students enrolled in IT make up the people who experience the maximum amount anxiety compared to other majors, many of which are women.
- Computer Science has almost an equal number of students who experience anxiety and those who do not.  
"""

#Panic attacks analysis amongst all courses

plt.figure(figsize=(8, 8))
sns.stripplot(x = 'Panic_Attack', y = 'Major', hue = 'Gender', data = df)
plt.show()
plt.savefig('panic.png')

"""
#Inference for Panic Attacks:
- The majors that have students experience the most panic attacks are Computer Science, Engineering and IT.
- It seems like nearly half of IT students experience panic attacks with near equal amounts shared between men an women.
- Panic attacks seem to primarly affect women more than men.

##Overall:
- It seems like the 3 most popular majors also tend to have the students who expereince the most mental health issues. Yet, these issues seem to affect women more than men.


##Examining Mental Health and How It May Relate To One's Current Year in School













"""

#Depression analysis amongst which the years. Which year of students does depression affect the most?

plt.figure(figsize=(14,7))
sns.boxplot(x = 'Year', y = 'Age', data = df,  hue = 'Depression')
plt.show()
plt.savefig('year_dep.png')

"""#Inference for Depression:
- Many Year 2 and 3 students experience depression.
- No Year 4 students experience depression
"""

#Anxiety analysis

plt.figure(figsize=(14,7))
sns.boxplot(x = 'Year', y = 'Age', data = df,  hue = 'Anxiety')
plt.show()
plt.savefig('year_anx.png')

"""
#Inference for Anxiety:
- Many year 3 students experience anxiety.
- No year 4 students experience anxiety."""

#Panic attacks
plt.figure(figsize=(14,7))
sns.boxplot(x = 'Year', y = 'Age', data = df,  hue = 'Panic_Attack')
plt.show()
plt.savefig('year_pan.png')

"""#Inference for Panic Attacks:
- Many year 2 and 3 students experience panic attacks; it appears that they experience it at about an even rate as well.

#Overall:
- No year 4 students experience panic attacks, anxiety, or depression except for those who are 24
- Year 3 students are more anxiety prone.
- Year 2 and 3 students experience the most depression and panic attacks.





# Examining the connection between one's GPA and mental health by Year
- Let's see which Year and age group have better or worse GPA's. From our earlier analysis, we can try to infer why it is what it is.
"""

#GPA and the impact it has on mental health
plt.figure(figsize=(14,7))
sns.boxplot(data=df, x="Year", y="Age", hue="GPA")
plt.show()
plt.savefig('year_gpa.png')

"""#Inference and thoughts:

- Students aged 18- 20 experience mental health problems with good GPA's
- Many Year 3 Students have GPAs under 2.0, could be because mental health tends to affect them most
- Students from Year 1 and Year 2 perform academically better having their GPAs above 2.5.

"""